### ISSUE TITLE
Does this module listen for hl7 messages?

### ISSUE THREAD

**Issue by 360disrupt** [evanlucas/nodengine-hl7#3]
Does it just parse the messages or does it create a server like this module:
https://github.com/ekryski/node-hl7
Which port is it using then? 

Would be awesome to add a basic example with a test message to the readme (I found this one, but I'm still confused: http://evanlucas.com/nodengine-hl7/).

**Comment by evanlucas** [comment]
It does not create a server. It is just a parser/builder.

Would definitely be open to a PR adding a basic example to the README :]

**Comment by 360disrupt** [comment]
I would be open to write one but unfortunately I didn't manage to send and receive a message in my app right now ;-) But it is good to know that this is a parser only. 

Maybe interesting for you that there are two more repos:

**Comment by 360disrupt** [comment]
Ok I have an example I will add it to the readme

**Comment by 360disrupt** [comment]
As mentioned I managed to receive and parse a message. But it seems that only the MSH Segment is read.

##Code
```
net = require('net')
hl7 = require('nodengine-hl7')
Parser = hl7.Parser
parser = new Parser()

parser.on('error', (err) ->
  console.log('Error parsing:', err)
)

# parser.on('messages', (messages) ->
#   console.log(messages)
#   console.log "l",messages.length
#   for message, index in messages
#     console.log("Message #{index}:", message)
# )

parser.on('message', (message) ->
  console.log('Message:', message)
)

createServer = () ->
  server = net.createServer((stream) ->
    stream.setEncoding 'utf8'
    stream.addListener 'connect', ->
      console.log 'Client connected'
      return

    stream.pipe(parser)

    stream.addListener 'end', ->
      console.log 'Client disconnected'
      stream.end()
      return
    return
  )
  server.listen 59895

createServer()
```

## Message Received
```
{ segments: 
   [ { delimiters: [Object],
       _raw: 'MSH|^~\\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|\r\nPID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|\r\nNK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||\r\nPV1||O|168 ~219~C~PMA^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853\r\nMSH|^~\\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|\r\nPID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|\r\nNK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||\r\nPV1||O|168 ~219~C~PMA^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853\r',
       parsed: [Object] } ],
  segmentTypes: [ 'MSH' ],
  header: 
   { delimiters: 
      { segment: '\r',
        field: '|',
        component: '^',
        subcomponent: '\\',
        repetition: '^',
        escape: '~' },
     _raw: 'MSH|^~\\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|\r\nPID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|\r\nNK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||\r\nPV1||O|168 ~219~C~PMA^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853\r\nMSH|^~\\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04|1817457|D|2.5|\r\nPID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|\r\nNK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||\r\nPV1||O|168 ~219~C~PMA^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853\r',
     parsed: 
      { SegmentType: 'MSH',
        EncodingCharacters: '|^~\\&',
        SendingApplication: 'EPIC',
        SendingFacility: 'EPICADT',
        ReceivingApplication: 'SMS',
        ReceivingFacility: 'SMSADT',
        DateTime: '199912271408',
        Security: 'CHARRIS',
        MessageType: 'ADT^A04',
        MessageControlID: '1817457',
        ProcessingID: 'D',
        VersionID: '2.5',
        SequenceNumber: '\r\nPID',
        ContinuationPointer: '',
        AcceptAcknowledgementType: '0493575^^^2^ID 1',
        ApplicationAcknowledgementType: '454721',
        CountryCode: '',
        CharacterSet: 'DOE^JOHN^^^^',
        PrincipalLanguage: 'DOE^JOHN^^^^',
        AlternateCharacterSetHandlingScheme: '19480203' } } }
```

**Comment by evanlucas** [comment]
Yea, so you would need to make sure you split on `\r` 

https://github.com/evanlucas/nodengine-hl7/blob/master/test/parser.js has a good example of using the `split` package for doing exactly this.

**Comment by 360disrupt** [comment]
Ok thank you, now I got it basically working with HL7 Inspector:
`stream.pipe(split(/\r/)).pipe(parser)``

### Splitting

With HL7 Soup it seems to split the segments incorrect. I receive errors of invalid segment types, it seems to cut off s.th. I piped it to stdout to see if there is a diff. but it looks the same when logged.

### Is it supposed to split into subfields:
E.g.
`PID||77291|PATID1234^9^55A||Smith^Willian^A^III||19720415|M-||2106-3|555 Upper Harbour Rd^^Springfield^NC^3401-540|NN|(919)479-4354|(919)371-654~(919)377-3455||S|AGN|PATID12345001^2^R10|1234567890|A-84334^NC`

becomes at the moment:
``` 
...
Name: 'Smith^Barbara^K',
...
```

If so I'm doing s.th. wrong. If not I will add this on certain fields and create a pull req.

**Comment by evanlucas** [comment]
It does not currently split into subfields. I am definitely open to a PR though. Not sure on the HL7 Soup issue though. Do you have a reliable test case where this is happening?

**Comment by 360disrupt** [comment]
I have a clue whats going on.
According to http://www.bluesock.org/~willg/dev/ascii.html Linux, Windows and Mac have diff. Carriage Returns:
`Unix end of line sequence: \n`
`Mac end of line sequence: \r`
`Windows end of line sequence:  \r\n`

I launch HL7 Soup from parallels (Windows) and HL7 Inspector from my OSX.

I have seen that in another repo (https://github.com/amida-tech/hl7/blob/master/example.js) they split on `\r` and join on '\n'. I don't know why they use join yet but the later solution works with and without (so it is not necessary).

solution A works on windows but not on a mac
`stream.pipe(split(/\n/)).pipe(joinStream(/\r/)).pipe(parser)` 
or
`stream.pipe(split(/\n\r/)).pipe(parser)` 

solution B works on a mac but not on windows
stream.pipe(split(/\r/)).pipe(joinStream(/\n/)).pipe(parser) #Win 

## Working Solution
So what I do now is to make both messages similar first and then split:
```
net = require('net')
hl7 = require('nodengine-hl7')
split = require('split')
replaceStream = require('replacestream')
Parser = hl7.Parser
parser = new Parser()
...
 stream.pipe(replaceStream(/\r\n/g, "\r")).pipe(replaceStream(/\n/g, "\r")).pipe(split(/\r/)).pipe(parser)
```

**Comment by paulinder** [comment]
@360disrupt Thanks for documenting this.
