### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by 360disrupt** [evanlucas/nodengine-hl7#5]
I don't see the project running under a special license here on Github, but I've seen that the segments are under copyright. On NPM it is under GNU license, with the restriciton to modify the code:
`Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.` So I guess I can use this in a commercial project? Than I would also contribute to the project in JS.

Maybe a good idea to add that.

**Comment by evanlucas** [comment]
v3.x is licensed under the MIT license. You are free to use it in a commercial project. I am also definitely open to contributions. :]
